name: nvchecker

on:
  push:
    paths:
      - .github/workflows/nvchecker.yaml
    branches:
      - master
  schedule:
    - cron: "0 3,10 * * *"

jobs:
  nvcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Use Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.2.1
      - name: Run install
        run: |
          pnpm i
      - name: Run test
        run: |
          pnpm test
      - name: Check versions
        run: |
          pnpx package-up-version
